### ISSUE TITLE
Quelques questions

### ISSUE THREAD

**Issue by TheCuteOwl** [ambr0sial/femboyaccess#1]
j'ai vue que tu m'as follow et que je travaille sur un RAT, j'aurai le droit de m'inspirer du tiens par hasard (pour quelque fonctionnalité, je volerai pas du code)

**Comment by ambr0sial** [comment]
coucouu! désolée j'avais pas vu le message- je savais pas que tu étais français(e) d'ailleurs!
bien sûr pourquoi pas mdrr, c'est fun de créer un RAT qui utilise Discord en C2, genre vraiment- inspire-toi du mien pour faire le tien si tu veux!!
btw si tu veux mon discord: waw#5437

**Comment by TheCuteOwl** [comment]
Haha, merci, ouai, même sur mon profil il y a marqué que je suis au canada, alors que non xD
va si je t'ajoute et merci encore
