### ISSUE TITLE
cmd doesn't work maybe add shell to execute PowerShell commands or anything to download a file and run it on the victim pc

### ISSUE THREAD

**Issue by Agonyxxx** [ambr0sial/femboyaccess#13]
cmd doesn't work maybe add shell to execute PowerShell commands or anything to download a file and run it on the victim pc and no run <file> doesn't work

**Comment by ambr0sial** [comment]
hi, yeah i know im sorry, it was added to the command list during development but got occupied with other features, and then forgot to remove it from the list before publishing. my bad for the confusion, but maybe i'll add the shell command in a future update! closing this for now, feel free to reopen it anytime.
