### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by StuKit** [ambr0sial/femboyaccess#6]
J'arrive pas a rajouter des nouvelles fonctionnalités au truc de base, il suffit pas de mettre un nouveau "if message stats with "exemple": " un truc du genre ? Quand je le fait ça rends juste le code de cette partie jusqu'à la fin non fonctionnel, Si c'est pas ça fait faire comment ?

**Comment by ambr0sial** [comment]
salut! si si, c'est ça normalement. exemple
```py
if message.content.startswith("ping"):
    await message.reply(await femboyaccess("ping", "pong!"))
```
si jamais, la fonction `femboyaccess` que j'await quand j'envoie un message c'est un preset de message. le premier paramètre c'est le titre et le second paramètre est le contenu du message
