### ISSUE TITLE
Add Success Message to builder

### ISSUE THREAD

**Issue by iRaccoon13** [ambr0sial/femboyaccess#7]
I kept pressing build not realizing it was done! I would recommend adding a success message.

**Comment by ambr0sial** [comment]
sorry for the inconvenience, a success message was added to the builder!

**Comment by iRaccoon13** [comment]
It's fine! I've been searching for a discord rat or at least a token grabber that works with macOS, and none do.

**Comment by ambr0sial** [comment]
i honestly don't even know how macOS works, i'm sorryy-
i've always been with windows as a main OS. used a bit of linux distros but thats it

**Comment by iRaccoon13** [comment]
It's like linux with extra code from apple. I just need the built file to work on windows, but when I tried it on a VM, it did not work. Is there anything I am doing wrong?

**Comment by ambr0sial** [comment]
hey there! are you sure you didn't make any typo?? we were talking about macOS and suddenly you're talking about how to make it work on Windows.

so uhh i dont really know what could be causing the issue, can you try to start the file via a command prompt? (like, not just left-clicking on the file), it may or may not print what has happened.
the first thing that goes through my mind is you don't have all of the libraries requirements on the VM. unfortunately, unless it is compiled into an .exe using a tool like Nuitka, the "victim" WILL need to have the libraries requirements using the following:
`pip install -r requirements.txt`

also thank you, i mean for me its pretty normal to answer without any kind of script or prepared answer lmao. have a good day!

**Comment by iRaccoon13** [comment]
I tried using pip, but it errored somewhere. I will try later.

**Comment by ambr0sial** [comment]
i'm closing the issue for now, but feel free to reopen it!
