### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iRaccoon13** [ambr0sial/femboyaccess#8]
I used the builder correctly but on my VM it's missing some modules that won't install with pip. What should I do? Also, what's ur discord so I don't spam ur email lol

**Comment by ambr0sial** [comment]
hey, yeah it's because the rat modules are actually under `modules/fem_imports.py` instead of being in the source file; that was an error

you should try again now, as i have updated the repository! if you still have issues, my discord is waw#5437
i'm closing this issue but feel free to reopen it
